version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"

  niconico-presenter:
    depends_on:
      - db
    image: niconico-presenter:latest
    ports:
      - '3000:3000'
    restart: always
    environment:
      DB_HOST: 'db'
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: niconico_presenter
volumes:
  db_data:
